name: Docker CI/CD

on:
  push:
    branches:
      - stable

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/wall-server:${{ github.sha }}

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop instance || true
            docker rm instance || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/wall-server:${{ github.sha }}
            docker run -d --name instance -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/wall-server:${{ github.sha }}
